mongodb/docs-rust

- .github/pull_request_template.md
- .github/workflows/check-autobuilder.yml
- .gitignore
- REVIEWING.md
- config/intersphinx.yaml
- config/redirects
- source/index.txt
Jira: https://jira.mongodb.org/browse/DOCSP-30504
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30504-configure-repo/
Build: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b193358d53f9c4af22a404
took the configuration files from `docs-golang`
> DOCSP-30504: setup rust repo base files

- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/includes/fundamentals/code-snippets/crud/delete.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-39542>
Staging - 
https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-39542-delete/fundamentals/crud/write-operations/delete/
https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-39542-delete/fundamentals/crud/write-operations/#std-label-rust-crud-write-operations
> DOCSP-39542: delete crud fundamentals

- source/index.txt
- source/op-error-handling.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30562>
Staging:
- https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30562-ops-error-handling/op-error-handling/
- https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30562-ops-error-handling/#operation-error-handling
had to manually run vale - fixed issues:
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
> DOCSP-30562: operation error handling

- source/fundamentals/authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33935>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/rust/DOCSP-33935-fix-client-api-link/fundamentals/authentication/#api-documentation
> DOCSP-33935: fix client api link on auth page

- source/facets.toml
- source/quick-start/facets.toml
- source/usage-examples/facets.toml
Hey @ccho-mongodb - here's the facets.toml files for the Rust Driver.  There are three because the /source/ directory was missing from the original facets.csv file.
JIRA - <https://jira.mongodb.org/browse/DOCSP-31343>
Staging - <https://preview-mongodbsarahemlin.gatsbyjs.io/rust/DOCSP-31343/>
> DOCSP-31343 added facets.toml files to docs-rust

- source/fundamentals/performance.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31470>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-31470-conn-pool-perf/fundamentals/performance/#connection-pool
> DOCSP-31470: describe connection pool in perf page

- source/fundamentals/crud/read-operations/cursor.txt
- source/fundamentals/crud/read-operations/query.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/includes/fundamentals/code-snippets/crud/cursor.rs
- source/includes/fundamentals/code-snippets/crud/insert.rs
- source/includes/fundamentals/code-snippets/crud/query.rs
- source/includes/fundamentals/code-snippets/crud/retrieve.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-33480>
Staging:
-  https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-33480/fundamentals/crud/read-operations/retrieve/
- https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-33480/fundamentals/crud/read-operations/query/
- https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-33480/fundamentals/crud/read-operations/cursor/
- https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-33480/fundamentals/crud/write-operations/insert/
> [Rust] use structs to model data instead of Document in CRUD fundamentals

- source/fundamentals/performance.txt
- source/fundamentals/serialization.txt
I also included a small terminology fix in this PR (derive statement -> derive attribute)
JIRA - <https://jira.mongodb.org/browse/DOCSP-35254>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-35254-pool-subsections/fundamentals/performance/#std-label-rust-performance-pool>
> DOCSP-35254: Connection pooling subsections

- source/faq.txt
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30557>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-30557-faq/faq/>
> DOCSP-30557: FAQ

- source/connection-troubleshooting.txt
JIRA - None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/rust/011824-typo-fix/connection-troubleshooting/ (no changes)
> fix meta keywords typo

- source/fundamentals/aggregation.txt
- source/fundamentals/connections/connection-options.txt
- source/fundamentals/crud/compound-operations.txt
- source/fundamentals/crud/read-operations/query.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/database-collection.txt
- source/fundamentals/enterprise-auth.txt
- source/fundamentals/stable-api.txt
- source/fundamentals/tracing-logging.txt
- source/index.txt
- source/issues-and-help.txt
- source/quick-start/connect-to-mongodb.txt
- source/quick-start/create-a-connection-string.txt
- source/quick-start/create-a-deployment.txt
- source/quick-start/download-and-install.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33478>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-33478-resolve-all-vale-issues/)
> DOCSP-33478: fix vale issues

- REVIEWING.md
- source/includes/fundamentals-sections.rst
Updated a couple page links that were commented out of the Fundamentals item bulleted list.
Updated the REVIEWING.md to clarify when to seek technical reviews.
JIRA - None
Staging:
- [Landing page](https://preview-mongodbcchomongodb.gatsbyjs.io/rust/012424-add-missing-list-items/#fundamentals)
- [Fundamentals drawer page](https://preview-mongodbcchomongodb.gatsbyjs.io/rust/012424-add-missing-list-items/fundamentals/)
> 012424: add missing list items and update REVIEWING.md

- source/includes/quick-start/troubleshoot.rst
Note: The feedback widget hasn't been updated in the staging environment.
JIRA - <https://jira.mongodb.org/browse/DOCSP-36574>
Staging:
[Quick Start > Download and Install](https://preview-mongodbcchomongodb.gatsbyjs.io/node/DOCSP-36573-feedback-widget-title/quick-start/download-and-install/)
> DOCSP-36574: Update feedback widget name

- source/fundamentals/aggregation.txt
- source/fundamentals/collations.txt
- source/fundamentals/connections/connection-guide.txt
- source/fundamentals/crud/read-operations/cursor.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/database-collection.txt
- source/fundamentals/stable-api.txt
- source/op-error-handling.txt
- source/usage-examples.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36851>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-36851-fy2025q1-typos/
> DOCSP-36851: fy2025q1 typos

- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/bulk.txt
- source/includes/fundamentals/code-snippets/crud/bulk.rs
JIRA - https://jira.mongodb.org/browse/DOCSP-39895
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-39895-bulk-write-guide/fundamentals/crud/write-operations/bulk/
> DOCSP-39895: Bulk write guide

- source/fundamentals/runtimes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39854
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-39854-tokio-runtime/fundamentals/runtimes/
> DOCSP-39854: Remove async-std runtime support

- source/fundamentals/gridfs.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39860
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-39860-read-write-concern-methods/fundamentals/gridfs/
Note: the GridFS guide is the only page that this change applies to; all other examples already use helper methods to specify read/write concerns
> DOCSP-39860: Read/write concern helper methods

- source/quick-start.txt
- source/quick-start/connect-to-mongodb.txt
- source/quick-start/create-a-connection-string.txt
- source/quick-start/create-a-deployment.txt
- source/quick-start/download-and-install.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41681>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/rust/DOCSP-41681-button/quick-start/>
> DOCSP-41681: Remove Green Buttons

- source/fundamentals/authentication.txt
- source/fundamentals/connections/network-compression.txt
- source/includes/fundamentals/code-snippets/auth.rs
- source/quick-start/create-a-connection-string.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-42378
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-42378-username-password/
> DOCSP-42378: Update username/password placeholders

- config/redirects
- snooty.toml
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43209
Staging - https://preview-mongodbmongokart.gatsbyjs.io/rust/docsp-43209-v3.1/whats-new/
> DOCSP-43209 - v3.1

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/includes/fundamentals/code-snippets/crud/skip.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-43425>
Staging - <https://deploy-preview-133--docs-rust.netlify.app/fundamentals/crud/read-operations/skip/>
> DOCSP-43424 Skip returned results

- source/fundamentals/transactions.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44627
Staging - https://deploy-preview-132--docs-rust.netlify.app/fundamentals/transactions/#methods
> DOCSP-44627: Add retry information

- source/fundamentals/stable-api.txt
- source/includes/fundamentals/code-snippets/stable-api-behavior.rs
- source/includes/fundamentals/code-snippets/stable-api.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-44854>
Staging - https://deploy-preview-136--docs-rust.netlify.app/fundamentals/stable-api/#stable-api-options-example
> DOCSP-44854: fix stable api options code

- source/fundamentals/connections/tls.txt
- source/fundamentals/performance.txt
- source/includes/fundamentals/code-snippets/auth.rs
- source/includes/fundamentals/code-snippets/connection-async.rs
- source/includes/fundamentals/code-snippets/enterprise-auth.rs
- source/includes/fundamentals/code-snippets/network-compression.rs
- source/includes/fundamentals/code-snippets/tls.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-44855>
Staging - https://deploy-preview-138--docs-rust.netlify.app/fundamentals/authentication/
Expanded scope to change all instances of `parse_async`
> DOCSP-44855: replace parse_async

- source/includes/fundamentals/code-snippets/aggregation.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-44862>
Staging - <https://deploy-preview-141--docs-rust.netlify.app/fundamentals/aggregation/>
> DOCSP-44862 Update aggregation code examples

- source/fundamentals/crud/read-operations/skip.txt
- source/includes/usage-examples/code-snippets/find-async.rs
- source/includes/usage-examples/code-snippets/find-one-async.rs
- source/includes/usage-examples/code-snippets/find-one-sync.rs
- source/includes/usage-examples/code-snippets/find-sync.rs
- source/usage-examples/find.txt
- source/usage-examples/findOne.txt
*Note*: new structure was approved by the PM
JIRA -https://jira.mongodb.org/browse/DOCSP-44963
Staging - 
https://deploy-preview-137--docs-rust.netlify.app/usage-examples/findOne/
https://deploy-preview-137--docs-rust.netlify.app/usage-examples/find/
> DOCSP-44963: Data modeling in find usage examples

- source/includes/usage-examples/code-snippets/replace-async.rs
- source/includes/usage-examples/code-snippets/replace-sync.rs
- source/includes/usage-examples/code-snippets/update-many-async.rs
- source/includes/usage-examples/code-snippets/update-many-sync.rs
- source/includes/usage-examples/code-snippets/update-one-async.rs
- source/includes/usage-examples/code-snippets/update-one-sync.rs
- source/usage-examples/find.txt
- source/usage-examples/findOne.txt
- source/usage-examples/replace.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44967
Staging - 
https://deploy-preview-143--docs-rust.netlify.app/usage-examples/updateOne/
https://deploy-preview-143--docs-rust.netlify.app/usage-examples/updateMany/
https://deploy-preview-143--docs-rust.netlify.app/usage-examples/replace/
> DOCSP-44967: Data modeling in update examples

- source/fundamentals.txt
- source/fundamentals/connections.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/indexes.txt
- source/fundamentals/monitoring.txt
- source/index.txt
- source/quick-start.txt
- source/usage-examples.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44951>
Staging - <https://deploy-preview-144--docs-rust.netlify.app/>
> DOCSP-44951 TOC Relabel

- source/includes/usage-examples/code-snippets/insert-many-async.rs
- source/includes/usage-examples/code-snippets/insert-many-sync.rs
- source/includes/usage-examples/code-snippets/insert-one-async.rs
- source/includes/usage-examples/code-snippets/insert-one-sync.rs
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44969
Staging - 
https://deploy-preview-154--docs-rust.netlify.app/usage-examples/insertOne/
https://deploy-preview-154--docs-rust.netlify.app/usage-examples/insertMany/
> DOCSP-44969: Modify insert usage examples

- source/fundamentals/enterprise-auth.txt
- source/includes/fundamentals/code-snippets/enterprise-auth.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-45153>
Staging - <https://deploy-preview-152--docs-rust.netlify.app/fundamentals/enterprise-auth/#mongodb-oidc>
> DOCSP-45153 Add MONGODB-OIDC

- source/fundamentals/crud/write-operations/delete.txt
- source/includes/fundamentals/code-snippets/crud/delete.rs
JIRA - https://jira.mongodb.org/browse/DOCSP-44859
Staging - https://deploy-preview-156--docs-rust.netlify.app/fundamentals/crud/write-operations/delete/
> DOCSP-44859: Add delete_one() example

- source/fundamentals/transactions.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45881
Staging - https://deploy-preview-160--docs-rust.netlify.app/fundamentals/transactions/
> DOCSP-45881: Parallel operations admonition

- source/includes/usage-examples/code-snippets/delete-many-async.rs
- source/includes/usage-examples/code-snippets/delete-many-sync.rs
- source/includes/usage-examples/code-snippets/delete-one-async.rs
- source/includes/usage-examples/code-snippets/delete-one-sync.rs
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44970
Staging -
https://deploy-preview-157--docs-rust.netlify.app/usage-examples/deleteOne/
https://deploy-preview-157--docs-rust.netlify.app/usage-examples/deleteMany/
> DOCSP-44970: Modify delete usage examples

- source/includes/usage-examples/code-snippets/count-async.rs
- source/includes/usage-examples/code-snippets/count-sync.rs
- source/includes/usage-examples/code-snippets/distinct-async.rs
- source/includes/usage-examples/code-snippets/distinct-sync.rs
- source/usage-examples/count.txt
- source/usage-examples/distinct.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44971
Staging - https://deploy-preview-163--docs-rust.netlify.app/usage-examples/count/
https://deploy-preview-163--docs-rust.netlify.app/usage-examples/distinct/
> DOCSP-44971: Count & distinct usage ex updates

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/includes/fundamentals/code-snippets/crud/skip.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-45854>
Staging - <https://deploy-preview-164--docs-rust.netlify.app/fundamentals/crud/read-operations/skip/>
> DOCSP-45854 Backport Skip Page

- source/fundamentals/enterprise-auth.txt
- source/includes/fundamentals/code-snippets/enterprise-auth.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-46683>
Staging - <https://deploy-preview-166--docs-rust.netlify.app/fundamentals/enterprise-auth/>
> DOCSP-46683: Kubernetes support for OIDC

- source/fundamentals/authentication.txt
- source/includes/fundamentals/code-snippets/auth.rs
JIRA - https://jira.mongodb.org/browse/DOCSP-44856
Staging - https://deploy-preview-167--docs-rust.netlify.app/fundamentals/authentication/
> DOCSP-44856: x509 authentication fixes

- source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48304>
Staging - <https://deploy-preview-172--docs-rust.netlify.app/compatibility/>
> DOCSP-48304 Add note about MSRV compatibility

- source/fundamentals/crud/web-app-tutorial.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-52058>
<li><a href=https://deploy-preview-194--docs-rust.netlify.app/fundamentals/crud/web-app-tutorial>fundamentals/crud/web-app-tutorial</a></li>
> DOCSP-52058 CRUD app with Rocket title

- snooty.toml
- source/api.txt
- source/fundamentals/connections.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/monitoring.txt
- source/view-source.txt
JIRA:
- <https://jira.mongodb.org/browse/DOCSP-51270>
- <https://jira.mongodb.org/browse/DOCSP-51271>
- <https://jira.mongodb.org/browse/DOCSP-51272>
- <https://jira.mongodb.org/browse/DOCSP-51276>
- <https://jira.mongodb.org/browse/DOCSP-51275>
- <https://jira.mongodb.org/browse/DOCSP-51273>
- <https://jira.mongodb.org/browse/DOCSP-51274>
<li><a href=https://deploy-preview-196--docs-rust.netlify.app/api>api</a></li><li><a href=https://deploy-preview-196--docs-rust.netlify.app/fundamentals/connections>fundamentals/connections</a></li><li><a href=https://deploy-preview-196--docs-rust.netlify.app/fundamentals/crud>fundamentals/crud</a></li><li><a …
> DOCSP-51276 >100 Words Page Fixes
