mongodb/docs-rust

.github/workflows/copy-compat-to-docs-shared.yml, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30563>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30563-link-api/) + see left side nav
=> DOCSP-30563: link to api docs

source/fundamentals.txt, source/includes/fundamentals-sections.rst, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30521>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30521-fundamentals-landing/#fundamentals
=> DOCSP-30521: fundamentals landing page

snooty.toml, source/fundamentals.txt, source/fundamentals/crud.txt, source/includes/fundamentals-sections.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-30533>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30533-crud-landing/fundamentals/crud/) & check the left hand nav and [index](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30533-crud-landing/#fundamentals)
=> DOCSP-30533: crud landing

.gitignore, snooty.toml, source/compatibility.txt, source/includes/language-compatibility-table-rust.rst, source/includes/mongodb-compatibility-table-rust.rst, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30559>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30559-compat/compatibility/
=> DOCSP-30559: compatibility

source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/index.txt, source/issues-and-help.txt
JIRA:
- [DOCSP-30534](https://jira.mongodb.org/browse/DOCSP-30534)
- [DOCSP-30535](https://jira.mongodb.org/browse/DOCSP-30535)
- [DOCSP-30558](https://jira.mongodb.org/browse/DOCSP-30558)
Staging:
- [Crud landing page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/30528-30534-30535-30558-remaining-setup/fundamentals/crud/)
- [Write ops landing page ](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/30528-30534-30535-30558-remaining-setup/fundamentals/crud/write-operations/)
- [Read ops landing page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/30528-30534-30535-30558-remaining-setup/fundamentals/crud/read-operations/)
- …
=> finish setup pages

source/code-snippets/crud/run-command.rs, source/fundamentals.txt, source/fundamentals/run-command.txt, source/includes/fundamentals-sections.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-30554>
[**Staging**](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30554-run-command/fundamentals/run-command/) & [index](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30554-run-command/#fundamentals), left hand nav
=> DOCSP-30554: run a command

source/fundamentals/crud/write-operations.txt, source/fundamentals/crud/write-operations/insert.txt, source/includes/fundamentals/automatic-creation.rst, source/includes/fundamentals/code-snippets/crud/insert.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30540>
[**Staging**](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30540-insert-funs/fundamentals/crud/write-operations/insert/), [WO landing](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30540-insert-funs/fundamentals/crud/write-operations/#std-label-rust-crud-write-operations), left nav
=> DOCSP-30540: insert fundamental guide

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fundamentals/automatic-creation.rst, source/includes/fundamentals/code-snippets/crud/retrieve.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30536>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30536-retrieve/fundamentals/crud/read-operations/retrieve/), [RO landing](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30536-retrieve/fundamentals/crud/read-operations/#std-label-rust-crud-read-operations), left nav
=> DOCSP-30536: retrieve data funs

source/fundamentals/crud.txt, source/fundamentals/crud/compound-operations.txt, source/includes/fundamentals/code-snippets/crud/compound.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30544>
**Staging**
- [page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30544-compound-crud/fundamentals/crud/compound-operations/) + see LH nav
- [crud landing](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30544-compound-crud/fundamentals/crud/)
[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c9733c87b3b360460a2cb9)
=> DOCSP-30544: compound operations (crud)

source/fundamentals/connections.txt, source/fundamentals/connections/connection-guide.txt, source/fundamentals/connections/network-compression.txt, source/includes/fundamentals/code-snippets/network-compression.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30526>
Staging:
- [NC page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30526-network-comp/fundamentals/connections/network-compression/)
- [connections landing page](https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30526-network-comp/fundamentals/connections/)
=> DOCSP-30526: network compression

source/fundamentals.txt, source/fundamentals/stable-api.txt, source/includes/fundamentals-sections.rst, source/includes/fundamentals/code-snippets/stable-api-behavior.rs, source/includes/fundamentals/code-snippets/stable-api.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30532>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30532-stable-api/fundamentals/stable-api/
=> DOCSP-30532 Stable API

source/compatibility.txt, source/includes/lifecycle-schedule-callout.rst
Note: uncertain why the vale check thinks there aren't any changes from the base commit.
JIRA - <https://jira.mongodb.org/browse/DOCSP-DOCSP-30911>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/rust/DOCSP-30911-server-support/compatibility/#mongodb-compatibility
=> DOCSP-30911: Add server lifecycle support callout

source/fundamentals/authentication.txt, source/fundamentals/crud/read-operations/cursor.txt, source/includes/fundamentals/code-snippets/quick-reference-async.rs, source/includes/fundamentals/code-snippets/quick-reference-sync.rs, source/index.txt, source/quick-reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30507>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30507-quick-reference/quick-reference/>
=> DOCSP-30507: Quick Reference

source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fundamentals/code-snippets/crud/retrieve.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30536>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/DOCSP-30536-retrieve-tech-review/fundamentals/crud/read-operations/retrieve/>
=> DOCSP-30536: Retrieve guide tech review

source/fundamentals/stable-api.txt
Responding to KA comments in #25 
JIRA - <https://jira.mongodb.org/browse/DOCSP-30532>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30532-stable-api-tech-review/fundamentals/stable-api/
=> DOCSP-30532: stable api tech review

source/includes/fundamentals/code-snippets/crud/delete.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30542>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30542-delete-tech-review/fundamentals/crud/write-operations/delete/
=> DOCSP-30542: delete funs KA tech review 

source/fundamentals/run-command.txt, source/includes/fundamentals/code-snippets/aggregation.rs, source/includes/fundamentals/code-snippets/crud/insert.rs, source/includes/fundamentals/code-snippets/crud/query.rs, source/includes/fundamentals/code-snippets/crud/retrieve.rs, source/includes/fundamentals/code-snippets/db-coll.rs, source/includes/fundamentals/code-snippets/run-command.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30531>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30531-db-coll-tech-review/fundamentals/database-collection/
=> DOCSP-30531: IA tech review

source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/crud/write-operations/change.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/schema-validation.txt, source/includes/fundamentals-sections.rst, source/includes/fundamentals/code-snippets/schema-validation.rs
A duplicate of [this PR](https://github.com/mongodb/docs-rust/pull/22) that was merged prematurely, then reverted.
JIRA - <https://jira.mongodb.org/browse/DOCSP-31848>
=> DOCSP-31848: Schema validation

source/includes/fundamentals/code-snippets/crud/insert.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30540>
=> DOCSP-30540: Insert guide tech review

source/fundamentals/crud/read-operations/query.txt, source/includes/fundamentals/code-snippets/crud/query.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-31495>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-31495-query-tech-review/fundamentals/crud/read-operations/query/
=> DOCSP-31495: specify query technical review

source/includes/fundamentals/code-snippets/crud/change.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30541>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/rust/docsworker-xlarge/master/fundamentals/crud/write-operations/change/>
=> DOCSP-30541: Change guide tech review

source/includes/fundamentals/code-snippets/aggregation.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30546>
=> DOCSP-30546: Aggregation tech review

source/includes/fundamentals/code-snippets/run-command.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30554>
=> Run command tech review

source/fundamentals/connections/connection-guide.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30523>
=> Connection guide tech review

source/includes/quick-start/code-snippets/connect-async.rs, source/includes/quick-start/code-snippets/connect-sync.rs, source/quick-start/connect-to-mongodb.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30505>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30505-QS-tech-review/quick-start/connect-to-mongodb/#create-your-rust-application
=> DOCSP-30505: quickstart tech review IA

source/connection-troubleshooting.txt, source/fundamentals.txt, source/fundamentals/aggregation.txt, source/fundamentals/authentication.txt, source/fundamentals/connections/connection-guide.txt, source/fundamentals/connections/connection-options.txt, source/fundamentals/connections/network-compression.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/query.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/write-operations/change.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/database-collection.txt, source/fundamentals/enterprise-auth.txt, source/fundamentals/run-command.txt, source/fundamentals/schema-validation.txt, source/fundamentals/serialization.txt, source/fundamentals/tracing-logging.txt, source/includes/fundamentals-sections.rst, source/includes/fundamentals/code-snippets/aggregation.rs, source/includes/fundamentals/code-snippets/crud/query.rs, source/op-error-handling.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31602>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-31602-cleanup-v1/
=> DOCSP-31602: cleanup for v1

source/connection-troubleshooting.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30560>
=> DOCSP-30560: Connection troubleshooting tech review

source/connection-troubleshooting.txt, source/fundamentals/authentication.txt, source/fundamentals/connections/connection-options.txt, source/fundamentals/enterprise-auth.txt, source/fundamentals/performance.txt, source/fundamentals/run-command.txt, source/fundamentals/schema-validation.txt, source/includes/fundamentals/code-snippets/performance-parallel.rs, source/includes/fundamentals/code-snippets/performance.rs, source/issues-and-help.txt
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/final-v1-cleanup/
=> Final v1 cleanup

source/fundamentals/aggregation.txt, source/fundamentals/authentication.txt, source/fundamentals/connections.txt, source/fundamentals/connections/connection-guide.txt, source/fundamentals/connections/connection-options.txt, source/fundamentals/connections/network-compression.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/query.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/write-operations/change.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/enterprise-auth.txt, source/fundamentals/stable-api.txt, source/fundamentals/tracing-logging.txt, source/includes/localhost-connection.rst, source/includes/quick-start/code-snippets/connect-async.rs, source/includes/quick-start/troubleshoot.rst, source/quick-reference.txt, source/quick-start/connect-to-mongodb.txt, source/quick-start/create-a-connection-string.txt, source/quick-start/download-and-install.txt
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/MW-proofreading-pre-publiush/
=> MW Proofreading edits

source/fundamentals/database-collection.txt, source/fundamentals/stable-api.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33649>
Staging:
[Stable API page](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-33649-broken-links/fundamentals/stable-api/#api-documentation)
DB/Collection page:
[dbspec](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-33649-broken-links/fundamentals/database-collection/#list-databases)
[collspec](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-33649-broken-links/fundamentals/database-collection/#list-collections)
=> DOCSP-33649: broken links

source/fundamentals.txt, source/fundamentals/indexes.txt, source/includes/fundamentals-sections.rst, source/includes/fundamentals/code-snippets/indexes.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30547>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30547-indexes/fundamentals/indexes/
[fundamentals sections list](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30547-indexes/#fundamentals)
=> DOCSP-30547: indexes

source/includes/usage-examples/code-snippets/find-async.rs, source/includes/usage-examples/code-snippets/find-sync.rs, source/usage-examples.txt, source/usage-examples/find.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30511>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-30511-find-usage-ex/usage-examples/find/>
=> DOCSP-30511: Find usage example

source/fundamentals/run-command.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33357>
Staging - [run a command page](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-33357-v2.7-content-changes/fundamentals/run-command/)
**This PR only addresses content changes to existing content. A what's new page is planned, where we will describe the version release features in more detail.**
=> DOCSP-33357: v2.7 content changes

source/fundamentals/crud/read-operations/query.txt, source/includes/usage-examples/code-snippets/count-async.rs, source/includes/usage-examples/code-snippets/count-sync.rs, source/usage-examples.txt, source/usage-examples/count.txt, source/usage-examples/find.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30519>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30519-count-usage-ex/usage-examples/count/
=> DOCSP-30519: count usage ex

source/includes/usage-examples/code-snippets/insert-one-async.rs, source/includes/usage-examples/code-snippets/insert-one-sync.rs, source/usage-examples.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt, source/usage-examples/replace.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30512>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30512-insert-usageex/usage-examples/insertOne/
=> DOCSP-30512: insert one usage ex

source/usage-examples/find.txt, source/usage-examples/findOne.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
=> Find operation fixes

source/includes/usage-examples/code-snippets/insert-many-async.rs, source/includes/usage-examples/code-snippets/insert-many-sync.rs, source/usage-examples.txt, source/usage-examples/insertMany.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30513>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-30513-insert-many-usage/usage-examples/insertMany/>
=> DOCSP-30513: Insert Many Usage Example

source/fundamentals.txt, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/fundamentals/performance.txt, source/fundamentals/runtimes.txt, source/fundamentals/serialization.txt, source/fundamentals/tracing-logging.txt, source/includes/fundamentals-sections.rst, source/includes/fundamentals/code-snippets/monitoring/command-subscribe.rs, source/includes/fundamentals/code-snippets/monitoring/cpm-subscribe.rs, source/includes/fundamentals/code-snippets/monitoring/sdam-subscribe.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30548>
Staging:
- [Cluster](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30548-monitoring/fundamentals/monitoring/cluster-monitoring/)
- [command](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30548-monitoring/fundamentals/monitoring/command-monitoring/)
- [connection pool](https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30548-monitoring/fundamentals/monitoring/connection-monitoring/)
=> DOCSP-30548: monitoring (command, connection pool, cluster topology)

source/includes/usage-examples/code-snippets/count-async.rs, source/includes/usage-examples/code-snippets/count-sync.rs, source/includes/usage-examples/code-snippets/distinct-async.rs, source/includes/usage-examples/code-snippets/distinct-sync.rs, source/usage-examples/count.txt, source/usage-examples/distinct.txt
=> distinct improvements and remove unnecessary structs

source/fundamentals/crud/write-operations/change.txt, source/includes/fundamentals/code-snippets/crud/change.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-34105>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-34105-objectid-example/fundamentals/crud/write-operations/change/#update-by-objectid-example>
=> DOCSP-34105: Update by ID example

source/includes/quick-start/code-snippets/connect-async.rs, source/includes/quick-start/code-snippets/connect-sync.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-34338>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-34338-fix-use-declarations/quick-start/connect-to-mongodb/>
=> DOCSP-34338: Update Quick Start code

source/fundamentals.txt, source/fundamentals/geo.txt, source/includes/fundamentals/code-snippets/crud/geo.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30539>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-30539-geo-search/fundamentals/geo/>
=> DOCSP-30539: Geospatial search

source/fundamentals/geo.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
=> Update Additional Resources header

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/text-search.txt, source/fundamentals/indexes.txt, source/includes/fundamentals/code-snippets/crud/text.rs, source/includes/fundamentals/code-snippets/indexes.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30538>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30538-text-search/fundamentals/crud/read-operations/text-search/
=> DOCSP-30538: text search

source/index.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30508>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30508-whats-new/whats-new/
=> DOCSP-30508: whats new

source/fundamentals/connections.txt, source/fundamentals/connections/network-compression.txt, source/fundamentals/connections/tls.txt, source/includes/fundamentals/code-snippets/tls.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-30527>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/rust/DOCSP-30527-tls/fundamentals/connections/tls/
=> DOCSP-30527: tls guide

source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34988>
Staging - [Compatibility Table](https://preview-mongodbcchomongodb.gatsbyjs.io/rust/DOCSP-34988-compatibility-sharedinclude/compatibility/)
=> DOCSP-34988: sharedinclude for version branch

source/connection-troubleshooting.txt
JIRA - None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/rust/011924-indentation-fix/connection-troubleshooting/
=> 011924 indentation fix

REVIEWING.md, source/includes/fundamentals-sections.rst
JIRA: None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/rust/012424-fundamentals-sections-order-fix/
=> 012424 fundamentals sections order fix

source/connection-troubleshooting.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replace.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
Note to the reviewer:
I checked that the code example renders and that the "view output" for each code example still works. I think the review could be focused on checking the indentation. The autobuilder doesn't currently report errors for the io-code-block, but the indentation prior to the changes looks incorrect.
Ignoring Vale issues and tags for now since this is an RST formatting-only bug fix.
JIRA - None
Staging:
- [Connection Troubleshooting](https://preview-mongodbcchomongodb.gatsbyjs.io/rust/020724-indentation-fix/connection-troubleshooting/)
- [Count](https://preview-mongodbcchomongodb.gatsbyjs.io/rust/020724-indentation-fix/usage-examples/count/)
- [Delete …
=> 020724 - fix code-block indentation

source/connection-troubleshooting.txt
Adds placeholder introduced in [this PR](https://github.com/10gen/docs-shared/pull/66/files).
JIRA - <https://jira.mongodb.org/browse/DOCSP-34709>
Staging - [Connection Troubleshooting](https://preview-mongodbcchomongodb.gatsbyjs.io/rust/DOCSP-34709-build-fix/connection-troubleshooting/#check-the-credentials-formatting) (fix not visible)
=> DOCSP-34709: build fix

snooty.toml, source/index.txt, source/quick-start.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38547
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/rust/DOCSP-38547-quickstart-name/
=> DOCSP-38547 Standardize Quick Start Name

source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/includes/fundamentals/code-snippets/monitoring/command-subscribe.rs, source/includes/fundamentals/code-snippets/monitoring/cpm-subscribe.rs, source/includes/fundamentals/code-snippets/monitoring/sdam-subscribe.rs
JIRA - https://jira.mongodb.org/browse/DOCSP-39853
Staging - 
https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-39853-eventhandler-type/fundamentals/monitoring/cluster-monitoring/
https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-39853-eventhandler-type/fundamentals/monitoring/command-monitoring/
https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-39853-eventhandler-type/fundamentals/monitoring/connection-monitoring/
=> DOCSP-39853: Updated monitoring api

source/fundamentals/runtimes.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39859
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/rust/DOCSP-39859-whats-new/whats-new/#std-label-rust-version-3.0
=> DOCSP-39859: What's New 3.0

source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41333>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/rust/v3.0/compatibility/>
=> [3.0] change shared includes

source/fundamentals/aggregation.txt, source/fundamentals/crud/read-operations/query.txt, source/fundamentals/crud/read-operations/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44857>
Staging - https://deploy-preview-139--docs-rust.netlify.app/fundamentals/crud/read-operations/retrieve/
=> Docsp 44857 improve retrieve

source/includes/fundamentals/code-snippets/crud/insert.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-44858>
Staging - https://deploy-preview-140--docs-rust.netlify.app/fundamentals/crud/write-operations/insert/#ordered-behavior-example
=> DOCSP-44858: fix ordered write code

source/includes/fundamentals/code-snippets/aggregation.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-44862>
=> DOCSP-44862 Backport changes to update aggregation examples

source/fundamentals.txt, source/fundamentals/connections.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/indexes.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44951>
=> [Backport v2.8] DOCSP-44951 TOC Relabel

source/fundamentals.txt, source/fundamentals/connections.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt
(cherry picked from commit 427afa7423d9ec861082e6a4d0b0a33f7f997980)
JIRA - <https://jira.mongodb.org/browse/DOCSP-44951>
=> [Backport v2.7] DOCSP-44951 TOC Relabel

source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/run-command.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42968>
Staging - Cursors <https://deploy-preview-150--docs-rust.netlify.app/fundamentals/crud/read-operations/cursor/>
Staging - Run Command <https://deploy-preview-150--docs-rust.netlify.app/fundamentals/run-command/>
=> DOCSP-42968 fixing nested components

config/redirects, snooty.toml, source/compatibility.txt, source/includes/language-compatibility-table-rust.rst, source/includes/mongodb-compatibility-table-rust.rst, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46541>
Staging - 
1. https://deploy-preview-161--docs-rust.netlify.app/whats-new/
2. https://deploy-preview-161--docs-rust.netlify.app/compatibility/
=> DOCSP-46541: v3.2 release

source/fundamentals/authentication.txt, source/fundamentals/connections/connection-options.txt, source/fundamentals/connections/tls.txt, source/includes/fundamentals/code-snippets/auth.rs, source/includes/fundamentals/code-snippets/tls.rs
JIRA - https://jira.mongodb.org/browse/DOCSP-46939
Staging - https://deploy-preview-165--docs-rust.netlify.app/fundamentals/connections/connection-options/
https://deploy-preview-165--docs-rust.netlify.app/fundamentals/connections/tls/#reference-certificates-in-a-client
https://deploy-preview-165--docs-rust.netlify.app/fundamentals/authentication/#mongodb-x509-mechanism
=> DOCSP-46939: tlsCertificateKeyFilePassword option

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/includes/fundamentals/code-snippets/crud/limit.rs
JIRA - <https://jira.mongodb.org/browse/DOCSP-45853>
Staging - <https://deploy-preview-168--docs-rust.netlify.app/fundamentals/crud/read-operations/limit/>
=> DOCSP-45853 Backport Limit Results

.github/pull_request_template.md
JIRA - <hhttps://jira.mongodb.org/browse/DOCSP-48933>
Staging - N/A
=> DOSCP-48933 Add PR checklist item for titles

source/fundamentals/connections/connection-guide.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48764>
Staging - <https://deploy-preview-174--docs-rust.netlify.app/fundamentals/connections/connection-guide/>
=> DOCSP-48764 Add Docker replica set connection note

source/fundamentals/connections.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48438>
Staging - https://deploy-preview-182--docs-rust.netlify.app/fundamentals/connections/
=> DOCSP-48438 - Add AWS Lambda link

source/fundamentals/authentication.txt, source/fundamentals/connections/network-compression.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/write-operations/change.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/indexes.txt, source/includes/mongodb-compatibility-table-rust.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-50027
<li><a href=https://deploy-preview-190--docs-rust.netlify.app/fundamentals/authentication>fundamentals/authentication</a></li><li><a href=https://deploy-preview-190--docs-rust.netlify.app/fundamentals/connections/network-compression>fundamentals/connections/network-compression</a></li><li><a href=https://deploy-preview-190--docs-rust.netlify.app/fundamentals/crud/compound-operations>fundamentals/crud/compound-operations</a></li><li><a href=https://deploy-preview-190--docs-rust.netlify.app/fundamentals/crud/write-operations/change>fundamentals/crud/write-operations/change</a></li><li><a href=https://deploy-preview-190--docs-rust.netlify.app/fundamentals …
=> DOCSP-50027: reduce EOL server mentions

source/fundamentals/aggregation.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50756
<li><a href=https://deploy-preview-192--docs-rust.netlify.app/fundamentals/aggregation>fundamentals/aggregation</a></li>
=> DOCSP-50756: Aggregation links

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-51239>
No pages to preview
=> DOCSP-51239: v3.2.4 patch
